// Foo License
// Code generated by processor/generate.go - DO NOT EDIT.
package lowercase

import (
	"github.com/andrewkroh/go-event-pipeline/pkg/processor"
	"github.com/andrewkroh/go-event-pipeline/pkg/processor/registry"
)

func init() {
	registry.MustRegister(processorName, New)
}

const (
	processorName = "lowercase"
)

// Config contains the configuration options for the lowercase processor.
type Config struct {
	// Source field to process.
	Field string `config:"field" validate:"required"`

	// If true and field does not exist or is null, the processor quietly
	// returns without modifying the document.
	IgnoreMissing bool `config:"ignore_missing"`

	// The field to assign the output value to, by default field is updated
	// in-place.
	TargetField string `config:"target_field"`
}

// InitDefaults initializes the configuration options to their default values.
func (c *Config) InitDefaults() {
	c.IgnoreMissing = false
}

// Lowercase converts a string to its lowercase equivalent. If the field is an
// array of strings, all members of the array will be converted.
type Lowercase struct {
	config Config
}

// New returns a new Lowercase processor.
func New(config Config) (*Lowercase, error) {
	return &Lowercase{config: config}, nil
}

// Config returns the Lowercase processor config.
func (p *Lowercase) Config() Config {
	return p.config
}

func (p *Lowercase) String() string {
	return processor.ConfigString(processorName, p.config)
}
