name: Go Test

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.11'

      - name: Make
        run: make

      - name: Check for uncommited changes
        run: git diff --quiet

